openapi-generators/openapi-python-client

CHANGELOG.md, openapi_python_client/openapi_parser/openapi.py, openapi_python_client/openapi_parser/properties.py, openapi_python_client/openapi_parser/responses.py, openapi_python_client/templates/async_endpoint_module.pyi, openapi_python_client/templates/endpoint_module.pyi, openapi_python_client/templates/model.pyi, tests/test_end_to_end/golden-master/my_test_api_client/api/default.py, tests/test_end_to_end/golden-master/my_test_api_client/api/users.py, tests/test_end_to_end/golden-master/my_test_api_client/async_api/default.py, tests/test_end_to_end/golden-master/my_test_api_client/async_api/users.py, tests/test_end_to_end/golden-master/my_test_api_client/models/a_model.py, tests/test_end_to_end/golden-master/my_test_api_client/models/abc_response.py, tests/test_end_to_end/golden-master/my_test_api_client/models/h_t_t_p_validation_error.py, tests/test_end_to_end/golden-master/my_test_api_client/models/other_model.py, tests/test_end_to_end/golden-master/my_test_api_client/models/validation_error.py, tests/test_end_to_end/test_end_to_end.py, tests/test_openapi_parser/test_properties.py, tests/test_openapi_parser/test_responses.py
This builds off of @acgray's work in #32.
=> Run mypy in end to end test

openapi_python_client/openapi_parser/openapi.py, openapi_python_client/openapi_parser/properties.py, openapi_python_client/openapi_parser/responses.py, openapi_python_client/templates/async_endpoint_module.pyi, openapi_python_client/templates/endpoint_module.pyi, openapi_python_client/templates/model.pyi, tests/test_end_to_end/golden-master/my_test_api_client/api/default.py, tests/test_end_to_end/golden-master/my_test_api_client/api/users.py, tests/test_end_to_end/golden-master/my_test_api_client/async_api/default.py, tests/test_end_to_end/golden-master/my_test_api_client/async_api/users.py, tests/test_end_to_end/golden-master/my_test_api_client/models/a_model.py, tests/test_end_to_end/golden-master/my_test_api_client/models/abc_response.py, tests/test_end_to_end/golden-master/my_test_api_client/models/h_t_t_p_validation_error.py, tests/test_end_to_end/golden-master/my_test_api_client/models/other_model.py, tests/test_end_to_end/golden-master/my_test_api_client/models/validation_error.py, tests/test_end_to_end/test_end_to_end.py, tests/test_openapi_parser/test_properties.py, tests/test_openapi_parser/test_responses.py
Small changes to eliminate mypy errors from the output
=> Type checking improvements

openapi_python_client/openapi_parser/openapi.py, openapi_python_client/openapi_parser/properties.py, openapi_python_client/templates/date_property.pyi, tests/test_openapi_parser/test_properties.py
Add support for `date` field format alongside `date-time`
=> Add support for `date` format in string types

CHANGELOG.md, openapi_python_client/__init__.py, openapi_python_client/openapi_parser/openapi.py, openapi_python_client/openapi_parser/properties.py, openapi_python_client/openapi_parser/reference.py, tests/test___init__.py, tests/test_openapi_parser/test_openapi.py, tests/test_openapi_parser/test_properties.py
A couple tweaks, improvements, and merge-resolutions on top of #31.
=> Improve Enum and Schema naming

openapi_python_client/__init__.py, openapi_python_client/openapi_parser/openapi.py, openapi_python_client/openapi_parser/properties.py, openapi_python_client/openapi_parser/reference.py, tests/test___init__.py, tests/test_openapi_parser/test_openapi.py, tests/test_openapi_parser/test_properties.py
* name schemas using the declaring property name if no `"title"` property is available. Currently the generator breaks when processing cases such as :
```
CoolFunModel:
type: object
properties: {...}
```
This will use `CoolFunModel` as the schema name in these cases.
* Conversely, for enum properties, if a `title` property is available in the property schema then ths this is used to name the enum.  This also addresses #21 - in the case where repeated property enums are derived from a single enum in a typed language (e.g. Java), if they have the same `title` they will be merged back into a single Python enum in the client.
=> Improvements to schema and enum naming

openapi_python_client/openapi_parser/responses.py, tests/test_openapi_parser/test_responses.py
=> allow no content responses

openapi_python_client/openapi_parser/properties.py, tests/test_openapi_parser/test_properties.py
=> allow unknown string format properties

CHANGELOG.md, openapi_python_client/__init__.py, openapi_python_client/openapi_parser/__init__.py, openapi_python_client/openapi_parser/openapi.py, openapi_python_client/openapi_parser/properties.py, openapi_python_client/openapi_parser/responses.py, openapi_python_client/templates/model.pyi, poetry.lock, pyproject.toml, tests/test___init__.py, tests/test_openapi_parser/test_openapi.py, tests/test_openapi_parser/test_properties.py, tests/test_openapi_parser/test_responses.py
Switches parsing to use a lib instead of custom dict logic. Closes #103
=> Refactor parsing

CHANGELOG.md, openapi_python_client/__init__.py, openapi_python_client/parser/openapi.py, tests/test___init__.py, tests/test_openapi_parser/test_openapi.py
=> Improve error message when OpenAPI document fails validation 

CHANGELOG.md, openapi_python_client/__init__.py, tests/test___init__.py
=> Better error handling when fetching documents

CHANGELOG.md, end_to_end_tests/fastapi_app/__init__.py, end_to_end_tests/fastapi_app/openapi.json, end_to_end_tests/golden-master/my_test_api_client/api/tests.py, end_to_end_tests/golden-master/my_test_api_client/async_api/tests.py, openapi_python_client/templates/async_endpoint_module.pyi, openapi_python_client/templates/endpoint_module.pyi, tests/test_templates/async_endpoint_module.py
Fixes #139.  Also changes the test tag in end to end tests to "tests" which makes more sense.
=> Fix JSON bodies in generated endpoints.

CHANGELOG.md, end_to_end_tests/fastapi_app/__init__.py, end_to_end_tests/fastapi_app/openapi.json, end_to_end_tests/golden-master/my_test_api_client/api/tests.py, end_to_end_tests/golden-master/my_test_api_client/async_api/tests.py, openapi_python_client/parser/responses.py, tests/test_openapi_parser/test_responses.py
=> Added support for octet-stream content type (#116)

CHANGELOG.md, end_to_end_tests/fastapi_app/__init__.py, end_to_end_tests/fastapi_app/openapi.json, end_to_end_tests/golden-master/my_test_api_client/api/tests.py, end_to_end_tests/golden-master/my_test_api_client/async_api/tests.py, openapi_python_client/parser/responses.py, tests/test_openapi_parser/test_responses.py
Adds support for lists of strings/numbers etc
Let me know if there should be some test changes or such. I haven't contributed to this repository before, so I'd appreciate some pointers if so. :)
=> feat: add support for lists of basic python types

end_to_end_tests/golden-master/my_test_api_client/api/tests.py, end_to_end_tests/golden-master/my_test_api_client/async_api/tests.py, openapi_python_client/templates/endpoint_macros.pyi
=> Remove trailing comma in endpoint_macros.pyi

CHANGELOG.md, end_to_end_tests/fastapi_app/__init__.py, end_to_end_tests/fastapi_app/openapi.json, end_to_end_tests/golden-master/my_test_api_client/models/a_model.py, openapi_python_client/parser/properties.py
A slightly modified cherry pick from #180 to fix the issue in 0.5
=> fix: import Optional when properties are nullable or not required

CHANGELOG.md, README.md, end_to_end_tests/config.yml, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/openapi.json, openapi_python_client/config.py, openapi_python_client/parser/properties.py, openapi_python_client/utils.py, tests/test_config.py, tests/test_openapi_parser/test_properties.py, tests/test_utils.py
This change allows the use of field names with leading characters (such as digits) which if converted directly into Python code would yield invalid identifiers.
Closes #203
=> Prepend a prefix to field names to allow use as Python identifiers

CHANGELOG.md, README.md, openapi_python_client/__init__.py, openapi_python_client/config.py, tests/test_config.py
Based on #225 with docs added.
=> Add a setting to override the package version

end_to_end_tests/golden-record-custom/custom_e2e/models/a_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/http_validation_error.py, end_to_end_tests/golden-record-custom/custom_e2e/models/test_inline_objectsjson_body.py, end_to_end_tests/golden-record-custom/custom_e2e/models/test_inline_objectsresponse_200.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/http_validation_error.py, end_to_end_tests/golden-record/my_test_api_client/models/test_inline_objectsjson_body.py, end_to_end_tests/golden-record/my_test_api_client/models/test_inline_objectsresponse_200.py, openapi_python_client/parser/properties/__init__.py, tests/test_parser/test_properties/test_init.py
=> Fixed issue with non-required fields in a model not being marked as such

end_to_end_tests/golden-record-custom/custom_e2e/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record-custom/custom_e2e/models/__init__.py, end_to_end_tests/golden-record-custom/custom_e2e/models/a_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/model_with_union_property.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property.py, end_to_end_tests/openapi.json, openapi_python_client/templates/property_templates/date_property.pyi, openapi_python_client/templates/property_templates/datetime_property.pyi, openapi_python_client/templates/property_templates/dict_property.pyi, openapi_python_client/templates/property_templates/enum_property.pyi, openapi_python_client/templates/property_templates/file_property.pyi, openapi_python_client/templates/property_templates/list_property.pyi, openapi_python_client/templates/property_templates/model_property.pyi, openapi_python_client/templates/property_templates/none_property.pyi, openapi_python_client/templates/property_templates/union_property.pyi
- Fix indentation of `transform`s on `inner_property`s of the `UnionProperty`
- Was overindented, causing error in generated models
- Update `transform` on all templates to take in a `declare_type` kwarg (default `True`) that determines if the first declaration of the property should include typedef
- Used by `union_property.pyi`'s `transform` to prevent mypy issues when calling the `transform` of its `inner_properties`
- Update `construct` on all templates to take a `initial_value` kwarg (defaults as appropriate, usually `None`, `[]` for lists)
- Used by `union_property.pyi`'s `construct` to prevent invalidly assigning `None` to the `inner_property`
- Update the `_parse_<inner_property>` function in `union_property`'s `construct` to use the passed subresource instead of the top level …
=> Fixes to union properties

end_to_end_tests/golden-record-custom/custom_e2e/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/openapi.json
* Add a query parameter in golden record to test schema with "anyOf": { "$ref": ...}
* Seems to me that there was some over indenting in `union_template.pyi`
* Mypy is unhappy, because in the `union_template.pyi` the `transform` macro from sub templates redefines the property, with a different type. How should I fix this?
=> Fix indentation in unions with refs

CHANGELOG.md, end_to_end_tests/golden-record-custom/README.md, end_to_end_tests/golden-record/README.md, openapi_python_client/templates/README.md
Match new style of calling endpoints. Closes #247
=> Update instructions in generated README.md

end_to_end_tests/golden-record-custom/custom_e2e/api/tests/test_inline_objects.py, end_to_end_tests/golden-record-custom/custom_e2e/models/__init__.py, end_to_end_tests/golden-record-custom/custom_e2e/models/test_inline_objects_json_body.py, end_to_end_tests/golden-record-custom/custom_e2e/models/test_inline_objects_response_200.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/test_inline_objects.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/test_inline_objects_json_body.py, end_to_end_tests/golden-record/my_test_api_client/models/test_inline_objects_response_200.py, openapi_python_client/parser/properties/__init__.py, tests/test_parser/test_properties/test_init.py
The new naming feature for classes with parent elements in `0.7.0` solves a problem for us, but the capitalization is not ideal.
Currently, if the parent is "`parent`" and the child is "`child`" it will generate classes like:
```python
class Parentchild:
```
After this change, it will be
```python
class ParentChild:
```
Which has better capitalization. This improves naming consistency when the model/enum is in-lined under a lower-case property and proper caps can't be enforced in the specs.
----
Also updated is list item property naming.
Before, it was doubling the child name when naming the items of a `child` list property of a `parent` class as:
```python
class ParentChildchildItem:
```
Now it just does
```python
class ParentChildItem:
```
=> Better naming of sub-model classes

end_to_end_tests/golden-record-custom/custom_e2e/models/an_enum.py, end_to_end_tests/golden-record-custom/custom_e2e/models/an_int_enum.py, end_to_end_tests/golden-record-custom/custom_e2e/models/different_enum.py, end_to_end_tests/golden-record/my_test_api_client/models/an_enum.py, end_to_end_tests/golden-record/my_test_api_client/models/an_int_enum.py, end_to_end_tests/golden-record/my_test_api_client/models/different_enum.py, openapi_python_client/templates/int_enum.pyi, openapi_python_client/templates/str_enum.pyi
Update both string and int enums to have a `__str__` method that return just the string representation of the value:
```python
def __str__(self) -> str:
return str(self.value)
```
----
This fixes a bug introduced in #241 (my bad 😬 ). As I [noted](https://github.com/triaxtec/openapi-python-client/pull/241#discussion_r525654722) on that PR, request bodies will be fine as `json.dumps` will convert the enums correctly. However it does not work for query string params - `urllib.parse.urlencode` (which `httpx` uses here) 
[just does `str(val)`](https://github.com/python/cpython/blob/3.9/Lib/urllib/parse.py#L941), which returns `"EnumClass.key"`.
So
```python
class SomeEnum(str, Enum):
val = "a_value"
some_endpoint.sync(client=api_client, some_query_string=SomeEnum.val)
```
would result in a …
=> Bugfix: Implement __str__ for enum props to fix query string

end_to_end_tests/golden-record-custom/custom_e2e/models/model_with_primitive_additional_properties.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_primitive_additional_properties.py, openapi_python_client/templates/property_templates/model_property.pyi
Bugfix for PR #252 
When switching to use `_<property>` as the temp holder for the `pop`ed dict value, I didn't update the `isinstance` check, so it was checking
```python
a_prop = UNSET
_a_prop = d.pop("aProp", UNSET)
if _a_prop is not None and not isinstance(a_prop, Unset):
a_prop = TheModel.from_dict(cast(Dict[str, Any], _response))
```
and `isinstance(a_prop, Unset)` would always evaluate to True so the value was never parsed.
Required adding type to model variable to please mypy
=> Fix bug in model property template that was not handling unset properly

CHANGELOG.md, end_to_end_tests/golden-record-custom/pyproject.toml, end_to_end_tests/golden-record/pyproject.toml, openapi_python_client/templates/pyproject.toml, openapi_python_client/templates/setup.py
The generated client now features a slightly more permissive version of `python-dateutil` to reduce dependency conflicts with some other projects. #298
=> Lower version requirements for python-dateutil in generated client #298

openapi_python_client/utils.py, tests/test_utils.py
I'm currently working with an api that uses [json:api](http://jsonapi.org). This uses a "self" attribute a lot. `python-attrs` fails to create an __init__ function for this because of a name collision on `self`. Although `self` is not a keyword in python, it's probably a good idea to not allow `self` as an attribute name. Alternatively, you could try to convince the folks developing `python-attrs` to allow for a `self` attribute by using a different name for the `self` parameter internally, like `pydantic` does.
This is a quick fix to just create a `self_` attribute instead.
=> Avoid attributes named "self"

CHANGELOG.md, end_to_end_tests/golden-record-custom/custom_e2e/models/model_with_union_property.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property.py, openapi_python_client/templates/property_templates/enum_property.pyi
When an `Enum` is `Unset` during deserialization, it causes an error by attempting to instantiate it from `UNSET`.
=> Handle Unset Enums when deserializing

CHANGELOG.md, openapi_python_client/parser/responses.py
[JSON:API](https://jsonapi.org/format/) has a media type of [application/vnd.api+json](https://www.iana.org/assignments/media-types/application/vnd.api+json), which is just json, so it can be parsed as such. This pull request adds it to the list of parsable media types.
=> Add "application/vnd.api+json" media type.

end_to_end_tests/golden-record-custom/custom_e2e/models/__init__.py, end_to_end_tests/golden-record-custom/custom_e2e/models/a_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_not_required_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_not_required_nullable_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_nullable_model.py, end_to_end_tests/golden-record-custom/custom_e2e/models/model_with_primitive_additional_properties.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model_model.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model_not_required_model.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model_not_required_nullable_model.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model_nullable_model.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_primitive_additional_properties.py, end_to_end_tests/openapi.json, openapi_python_client/templates/property_templates/model_property.pyi
Currently, the code only accounts for the `not required` case, not the `nullable` case.
This PR also adds E2E test coverage.
=> Fix nullable model properties in `from_dict` and `to_dict`

CHANGELOG.md, end_to_end_tests/golden-record-custom/custom_e2e/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record-custom/custom_e2e/api/tests/get_user_list.py, end_to_end_tests/golden-record-custom/custom_e2e/api/tests/int_enum_tests_int_enum_post.py, end_to_end_tests/golden-record-custom/custom_e2e/api/tests/optional_value_tests_optional_query_param.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_user_list.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/int_enum_tests_int_enum_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/optional_value_tests_optional_query_param.py, openapi_python_client/templates/endpoint_macros.py.jinja, openapi_python_client/templates/endpoint_module.py.jinja, tests/test_templates/endpoint_module.py
Closes #285. CC @bowenwr and @forest-benchling since this is my simple solution to an issue that plagues them. I believe aside from the type hinting being wrong in your SDK, this will solve the immediate functionality issue while bringing us more in line with the OpenAPI specification.
=> fix!: Omit any `None` passed as a query param in generated clients. 

end_to_end_tests/openapi.json, openapi_python_client/parser/properties/__init__.py, tests/test_parser/test_properties/test_init.py
Previously, it would silently create buggy code if duplicate models were generated with the same name; see https://github.com/triaxtec/openapi-python-client/pull/335 and https://github.com/triaxtec/openapi-python-client/issues/323.
=> fix: Fail when duplicate names are generated

CHANGELOG.md, end_to_end_tests/golden-record-custom/custom_e2e/api/tests/token_with_cookie_auth_token_with_cookie_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_booleans.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_floats.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_integers.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_strings.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_user_list.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/int_enum_tests_int_enum_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/no_response_tests_no_response_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/octet_stream_tests_octet_stream_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/optional_value_tests_optional_query_param.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/test_inline_objects.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/token_with_cookie_auth_token_with_cookie_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/unsupported_content_tests_unsupported_content_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_file_tests_upload_post.py, end_to_end_tests/openapi.json, openapi_python_client/parser/openapi.py, openapi_python_client/templates/endpoint_macros.py.jinja, openapi_python_client/templates/endpoint_module.py.jinja, tests/test_parser/test_openapi.py, tests/test_templates/endpoint_module.py
=> feat: Add support for cookie parameters

CHANGELOG.md, openapi_python_client/__init__.py, openapi_python_client/cli.py, tests/test___init__.py, tests/test_cli.py
If there are non-ASCII characters in openapi (eg: https://v1.api.tttt.one/openapi.json)
Garbled characters may appear in the generated client file.
To this end, add encoding parameter to cli，Similar problems can be ended by `--encoding=utf-8`
=> feat:  Add new client parameters: encoding

CONTRIBUTING.md
=> docs: Need to run task regen_custom

openapi_python_client/parser/properties/enum_property.py, tests/test_parser/test_properties/test_init.py
=> Support empty strings in enums

end_to_end_tests/golden-record/my_test_api_client/models/validation_error.py, openapi_python_client/utils.py, tests/test_utils.py
=> fix: Support attributes using builtin type names

pyproject.toml, setup.py
It seems that hings are more complicated than that. This shim setup.py does
allow the project to be pip -e installed but you don't get the entrypoints,
making it completely useless.
This reverts commit 915183dd181fc2c5619765e245c465a1765102fd.
=> Revert "build: Include a basic setup.py to allow editable installs during development (#370)"

end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/an_all_of_enum.py, end_to_end_tests/openapi.json, end_to_end_tests/regen_golden_record.py, openapi_python_client/parser/properties/__init__.py, tests/test_parser/test_properties/test_init.py
I discovered some issues with the handling of `allOf`, this should fix them!
=> fix: Errors in allOf behaviour

end_to_end_tests/golden-record/my_test_api_client/models/validation_error.py, openapi_python_client/utils.py, tests/test_utils.py
Closes #378 which was reported by @forest-benchling
=> feat!(generator): type and id are allowed as attribute names and will not be converted

end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_same_name_multiple_locations_param.py, end_to_end_tests/openapi.json, openapi_python_client/parser/openapi.py, openapi_python_client/parser/properties/property.py, openapi_python_client/schema/__init__.py, openapi_python_client/schema/openapi_schema_pydantic/header.py, openapi_python_client/schema/openapi_schema_pydantic/parameter.py, openapi_python_client/schema/parameter_location.py, tests/test_parser/test_openapi.py
=> fix(parser): Attempt to deduplicate endpoint parameters based on name and location (fixes #305)

CHANGELOG.md, pyproject.toml
Changelog generated by https://github.com/triaxtec/dobby😻 . It's also run through Prettier now, so some older entries are reformatted.
=> chore: Prep 0.9.0 release

pyproject.toml
Projects using black as a dependency and this library will no longer have to use the specific version of black that this library does.
Per discussion, and fixes #411
=> feat(deps): Soften black dependency for generated clients.

end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_any_json_properties.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_primitive_additional_properties.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_property_ref.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property_inlined.py, openapi_python_client/templates/property_templates/property_macros.py.jinja, openapi_python_client/templates/property_templates/union_property.py.jinja, tests/test_templates/test_property_templates/test_date_property/optional_nullable.py, tests/test_templates/test_property_templates/test_date_property/required_nullable.py
=> Fix deserialization of optional nullable properties

openapi_python_client/__main__.py, openapi_python_client/parser/openapi.py, openapi_python_client/parser/properties/converter.py, tests/test___main__.py, tests/test_parser/test_openapi.py
1. Fixes #414
2. Changes `__main__` to actually do what it's supposed to for debugging 😅
3. Catches attribute errors when converting defaults to prevent similar future crashes
4. Provides more detail in parse errors on endpoint bodies (needed while debugging)
=> fix(parser): Prevent crash when providing a non-string default to a string attribute. Fixes #414

end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model_with_properties_reference_that_are_not_object.py, end_to_end_tests/openapi.json, openapi_python_client/parser/properties/schemas.py, openapi_python_client/templates/model.py.jinja
Adapted from #418 to merge in changes on main and simplify new e2e test. Fixes #371
=> feat(parser): Allow references to non-object, non-enum types [#371][#418]

end_to_end_tests/golden-record/my_test_api_client/api/tests/post_form_data.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/a_form_data.py, end_to_end_tests/openapi.json, openapi_python_client/templates/endpoint_module.py.jinja
This PR aims to fix form data serialization. 
Form data model was serialized using `attr.asdict`, which is not aware of the internal type `UNSET` and was serializing `UNSET` references.
This PR replace the call to `attr.asdict`  with `<Model>.to_dict` method, which knows how to properly serialize `UNSET` values.
Before:
After:
=> Fix(template): form data model serialization

openapi_python_client/cli.py, tests/test_cli.py
For our case, we'd rather fail fast than have a potentially incomplete client. I'm open to opinions on the best interface here, like if the flag should be renamed.
=> feat: Add option to fail generating client if there are any warnings

end_to_end_tests/golden-record/my_test_api_client/models/a_model_with_properties_reference_that_are_not_object.py, openapi_python_client/parser/properties/__init__.py, openapi_python_client/utils.py, tests/test_utils.py
Keep "Response200" as "response_200", but don't make "s3config" become "s_3_config". :)
Related to the comments here: https://github.com/triaxtec/openapi-python-client/pull/375#issuecomment-831377313
=> Enhance split words

end_to_end_tests/custom-templates-golden-record/README.md, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/default/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/parameters/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/tests/__init__.py, end_to_end_tests/regen_golden_record.py, end_to_end_tests/test_custom_templates/api_init.py.jinja, end_to_end_tests/test_custom_templates/endpoint_init.py.jinja, end_to_end_tests/test_end_to_end.py, openapi_python_client/__init__.py, openapi_python_client/templates/README.md.jinja, openapi_python_client/templates/api_init.py.jinja, openapi_python_client/templates/package_init.py.jinja, openapi_python_client/templates/pyproject.toml.jinja, openapi_python_client/templates/setup.py.jinja, tests/test___init__.py
=> feat: Allow custom templates for API and endpoint `__init__` files.

end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/tag1/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/tag1/get_tag_with_number.py, end_to_end_tests/openapi.json, end_to_end_tests/test_end_to_end.py, openapi_python_client/config.py, openapi_python_client/parser/openapi.py, openapi_python_client/parser/properties/__init__.py, openapi_python_client/parser/properties/model_property.py, openapi_python_client/parser/properties/property.py, openapi_python_client/parser/responses.py, openapi_python_client/utils.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_config.py, tests/test_parser/test_openapi.py, tests/test_parser/test_properties/test_init.py, tests/test_parser/test_properties/test_model_property.py, tests/test_parser/test_properties/test_property.py, tests/test_parser/test_responses.py, tests/test_templates/test_property_templates/test_date_property/test_date_property.py, tests/test_utils.py
This PR is motivated to fix #428 but as part of that fix there are a few other changes:
1. More consistently name generated modules, __may be a breaking change__
2. Update mypy and add some now-separate typing modules (mostly just to increase refactor confidence)
3. Remove the last runtime global (field prefix)
4. Refactor impacted tests to be less fragile for the future
=> fix!: Normalize generated module names to allow more tags [#428]. Thanks @iamnoah!

end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/tests/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_multiple_files_tests_upload_post.py, end_to_end_tests/openapi.json, openapi_python_client/templates/property_templates/list_property.py.jinja
Fixes #451 though perhaps a better "fix" would be to disallow multipart request bodies with `type: array`?
=> fix: Support multipart requests with type: array

end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/all_of_sub_model.py, end_to_end_tests/golden-record/my_test_api_client/models/all_of_sub_model_type_enum.py, end_to_end_tests/golden-record/my_test_api_client/models/another_all_of_sub_model.py, end_to_end_tests/golden-record/my_test_api_client/models/another_all_of_sub_model_type.py, end_to_end_tests/golden-record/my_test_api_client/models/another_all_of_sub_model_type_enum.py, end_to_end_tests/golden-record/my_test_api_client/models/model_from_all_of.py, end_to_end_tests/openapi.json, openapi_python_client/parser/properties/model_property.py, pyproject.toml, tests/conftest.py, tests/test_parser/test_properties/test_model_property.py
Based on and closes #423. Closes #379.
=> feat: Allow allOf enums to be subsets of one another or their base types [#379, #423, #461]. Thanks @forest-benchling!

end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/parameters/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/delete_common_parameters_overriding_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_common_parameters_overriding_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_same_name_multiple_locations_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/multiple_path_parameters.py, end_to_end_tests/openapi.json, openapi_python_client/parser/openapi.py, openapi_python_client/templates/endpoint_macros.py.jinja, tests/test_parser/test_openapi.py
This replaces #429 so I can rebase and resolve conflicts.
=> feat: Allow path parameters to be positional args [#429]. Thanks @tsotnikov!

.github/workflows/checks.yml, end_to_end_tests/test_end_to_end.py
=> ci: Test on windows

end_to_end_tests/golden-record/README.md, openapi_python_client/templates/README.md.jinja
Sorry -- this is the most trivial of PRs but trailing whitespace triggers me lol.
=> style: remove trailing whitespace in README template

openapi_python_client/parser/properties/__init__.py, openapi_python_client/schema/__init__.py, openapi_python_client/schema/data_type.py, openapi_python_client/schema/openapi_schema_pydantic/schema.py, tests/test_parser/test_properties/test_init.py, tests/test_parser/test_properties/test_model_property.py, tests/test_schema/test_data_type.py
A little suggestion for type checking in the `Schema`: Looks like it is a task for `pydantic` in input. This is more obvious and allows to reduce test cases.
=> Feat: Schema datatypes validation by `pydantic`

README.md, openapi_python_client/__init__.py, openapi_python_client/config.py, tests/test___init__.py
=> Fix #479 and add post-generation customization config

end_to_end_tests/golden-record/my_test_api_client/api/default/get_common_parameters.py, end_to_end_tests/golden-record/my_test_api_client/api/default/post_common_parameters.py, end_to_end_tests/golden-record/my_test_api_client/api/location/get_location_query_optionality.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/delete_common_parameters_overriding_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_common_parameters_overriding_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_same_name_multiple_locations_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/multiple_path_parameters.py, end_to_end_tests/golden-record/my_test_api_client/api/tag1/get_tag_with_number.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_booleans.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_floats.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_integers.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_strings.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_user_list.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/int_enum_tests_int_enum_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/json_body_tests_json_body_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/no_response_tests_no_response_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/octet_stream_tests_octet_stream_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/post_form_data.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/test_inline_objects.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/token_with_cookie_auth_token_with_cookie_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/unsupported_content_tests_unsupported_content_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_file_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_multiple_files_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/api/true_/false_.py, openapi_python_client/templates/endpoint_module.py.jinja
=> fix: SSL verify argument to async clients [#510]. Thanks @fsvenson and @mvaught02!

openapi_python_client/cli.py, usage.md
Was trying to figure this out and had to look at the code.
=> docs: explain difference between update and generate

openapi_python_client/config.py, pyproject.toml, tests/test_config.py
=> fix: Relative paths to config files.

end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/tests/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/post_tests_json_body_string.py, end_to_end_tests/openapi.json, openapi_python_client/templates/endpoint_macros.py.jinja, openapi_python_client/templates/endpoint_module.py.jinja
=> fix: Basic types as JSON bodies and responses

end_to_end_tests/golden-record/my_test_api_client/api/default/get_common_parameters.py, end_to_end_tests/golden-record/my_test_api_client/api/default/post_common_parameters.py, end_to_end_tests/golden-record/my_test_api_client/api/location/get_location_query_optionality.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/delete_common_parameters_overriding_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_common_parameters_overriding_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/get_same_name_multiple_locations_param.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/multiple_path_parameters.py, end_to_end_tests/golden-record/my_test_api_client/api/tag1/get_tag_with_number.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_booleans.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_floats.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_integers.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_strings.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_user_list.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/int_enum_tests_int_enum_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/json_body_tests_json_body_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/no_response_tests_no_response_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/octet_stream_tests_octet_stream_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/post_form_data.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/post_tests_json_body_string.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/test_inline_objects.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/token_with_cookie_auth_token_with_cookie_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/unsupported_content_tests_unsupported_content_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_file_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_multiple_files_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/api/true_/false_.py, openapi_python_client/templates/endpoint_module.py.jinja
As described in #545 i changed every httpx call to use httpx.request instead of httpx.get/post/put/etc.
=> feat: Use httpx.request to allow bodies for all type of requests

end_to_end_tests/golden-record/pyproject.toml, integration-tests/pyproject.toml, openapi_python_client/templates/pyproject.toml.jinja, openapi_python_client/templates/setup.py.jinja, poetry.lock, pyproject.toml
BREAKING CHANGE: Python 3.6 is officially not supported. The minimum version has been updated to reflect this.
=> chore: Remove Reminaing Python 3.6 references

openapi_python_client/templates/setup.py.jinja
When openapi-python-client is used to with the
--meta=setup option the generated setup.py needs to
use setuptools.find_packages() to find the top-level
and all of the nested pacakges in the directory
so that distributions include them
=> fix: Include nested packages in generated setup.py (closes #575)

openapi_python_client/templates/property_templates/date_property.py.jinja, openapi_python_client/templates/property_templates/datetime_property.py.jinja
without this fix generate fail in black check!
=> remove bad indent space generate with jinja comments [BUGFIX]

CHANGELOG.md, openapi_python_client/schema/openapi_schema_pydantic/oauth_flow.py
Looks like the change before:
https://github.com/openapi-generators/openapi-python-client/commit/15c2fd5db2dd8afa6947cbf5a852a6f895f054db#diff-1a1a2865f336a376229eaffe0f56caac01c7a3a77602e07fe4a38fd550c6c318
Has been reverted:
https://github.com/openapi-generators/openapi-python-client/commit/0101a039c4f709977e136b3c0f5d186a63a7c6c5#diff-6676609c9c37705f6953ffcc9eb6d33164df50f241d4844c5665cf5ff4305995R16
As mentioned, relative URLs are supported in OpenAPI 3.0+:
https://github.com/swagger-api/swagger-ui/issues/5243
=> fix: Allow tokenUrl to be relative

openapi_python_client/schema/openapi_schema_pydantic/contact.py, openapi_python_client/schema/openapi_schema_pydantic/external_documentation.py, openapi_python_client/schema/openapi_schema_pydantic/info.py, openapi_python_client/schema/openapi_schema_pydantic/license.py, openapi_python_client/schema/openapi_schema_pydantic/oauth_flow.py, openapi_python_client/schema/openapi_schema_pydantic/security_scheme.py
Following up from https://github.com/openapi-generators/openapi-python-client/pull/618 - this doesn't quite bring the library into compliance with the spec yet as this rule applies to *all* URLs.
https://swagger.io/specification/#relative-references-in-urls
> **Relative References in URLs**
> Unless specified otherwise, all properties that are URLs MAY be relative references as defined by [RFC3986](https://tools.ietf.org/html/rfc3986#section-4.2). Relative references are resolved using the URLs defined in the [Server Object](https://swagger.io/specification/#server-object) as a Base URI.
There aren't (as of 3.0.3) any exceptions defined to this, so this PR removes all uses of `AnyUrl` and replaces them with `str`.
=> fix: Allow relative references in all URLs

end_to_end_tests/golden-record/my_test_api_client/api/location/get_location_header_types.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/get_location_header_types_int_enum_header.py, end_to_end_tests/golden-record/my_test_api_client/models/get_location_header_types_string_enum_header.py, end_to_end_tests/openapi.json, openapi_python_client/parser/properties/enum_property.py, openapi_python_client/templates/property_templates/enum_property.py.jinja
=> feat: Allow enums in headers

end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/all_of_has_properties_but_no_type.py, end_to_end_tests/golden-record/my_test_api_client/models/all_of_has_properties_but_no_type_type_enum.py, end_to_end_tests/openapi.json, openapi_python_client/parser/properties/__init__.py
Closes https://github.com/openapi-generators/openapi-python-client/issues/674
Not entirely sure if I did the end to end testing correctly since I got:
```
end_to_end_tests: task regen
Generating my-test-api-client
Usage: openapi-python-client update [OPTIONS]
Try 'openapi-python-client update --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value: Unable to parse config
```
But it generated the test files and the task e2e succeeded.
=> fix: If data.type is None but has data.properties, assume type is object

openapi_python_client/__init__.py
This makes `endpoint_collections_by_tag` available in every template (Instead of only a few selected places).
`openapi` is not immediately useful, but is being used on my custom templates
=> Add `endpoint_collections_by_tag` and `openapi` to the templating globals

.github/workflows/checks.yml, openapi_python_client/parser/properties/property.py, openapi_python_client/schema/parameter_location.py, openapi_python_client/templates/endpoint_module.py.jinja, poetry.lock, pyproject.toml, tests/test_parser/test_openapi.py
Python 3.11.0 has breaking changes around `repr()` and `str()` for enums, some of which is behavior we were relying on.
This PR fixes enough of the enums to get the tests passing again.
=> fix: Support Python 3.11.0

end_to_end_tests/openapi.json, openapi_python_client/parser/openapi.py, openapi_python_client/parser/responses.py, tests/test_parser/test_openapi.py
=> feat: Support any content type ending in `+json` [#706]. 

README.md, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/openapi.json, openapi_python_client/utils.py
There are 2 reasons for this change:
- leading underscores have special meaning and therefore we should prefix those properties to avoid unexpected semantics
- in my particular use case my team is working with a schema which has the following fields in an object: "field" and "_field" and current code strips leading underscore and produces invalid data object with 2 fields of the same name
=> fix: Treat leading underscore as a sign of invalid identifier

end_to_end_tests/golden-record/my_test_api_client/api/responses/post_responses_unions_simple_before_complex.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/callback_test.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_booleans.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_floats.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_integers.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_basic_list_of_strings.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/get_user_list.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/int_enum_tests_int_enum_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/json_body_tests_json_body_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/octet_stream_tests_octet_stream_get.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/post_tests_json_body_string.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/test_inline_objects.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_file_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/upload_multiple_files_tests_upload_post.py, integration-tests/integration_tests/api/body/post_body_multipart.py, integration-tests/integration_tests/api/parameters/post_parameters_header.py, openapi_python_client/templates/endpoint_macros.py.jinja, openapi_python_client/templates/endpoint_module.py.jinja
We only get `Response` objects from the `*_detailed()` functions.
=> fix: Remove Response[] from docstring of non-detailed functions

openapi_python_client/parser/openapi.py, openapi_python_client/utils.py, tests/test_parser/test_openapi.py, tests/test_utils.py
This PR allows to extract the content type safely removing any extra parameter like `charset` or `boundary`.
=> fix: Parsing endpoint content types with semicolon separator

end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/default/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/default/reserved_parameters.py, end_to_end_tests/openapi.json, openapi_python_client/parser/openapi.py
=> fix: Allow parameters named "client" and "url"

end_to_end_tests/openapi.json, openapi_python_client/parser/responses.py, tests/test_parser/test_responses.py
This resolves  #655  #809
Content-type with a version attribute appears to be very common in OpenAPI schemas generated for .Net applications.
=> feat: Support content-type with attributes (#655 #809). Thanks @sherbang!

end_to_end_tests/golden-record/my_test_api_client/types.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/types.py, integration-tests/integration_tests/types.py, openapi_python_client/templates/types.py.jinja
=> feat: Export `Unset` types from generated `types.py`

.changeset/fix_lists_within_unions.md, .changeset/simplify_type_checks_for_non_required_unions.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/golden-record/my_test_api_client/api/defaults/defaults_tests_defaults_post.py, end_to_end_tests/golden-record/my_test_api_client/api/location/get_location_query_optionality.py, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/body_upload_file_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property_inlined.py, openapi_python_client/parser/properties/list_property.py, openapi_python_client/parser/properties/union.py, openapi_python_client/templates/property_templates/date_property.py.jinja, openapi_python_client/templates/property_templates/datetime_property.py.jinja, openapi_python_client/templates/property_templates/enum_property.py.jinja, openapi_python_client/templates/property_templates/file_property.py.jinja, openapi_python_client/templates/property_templates/list_property.py.jinja, openapi_python_client/templates/property_templates/model_property.py.jinja, openapi_python_client/templates/property_templates/property_macros.py.jinja, openapi_python_client/templates/property_templates/union_property.py.jinja
Resolves #928 with two simple fixes:
* Adds `get_type_string()` to `ListProperty` based on the definition in `ModelProperty`, since both arrays and objects are JSON-serialized in multipart mode.
* Ensures that an empty list is used when `UNSET` is the default (initial) value when constructing a list property.
=> Nullable array support fixes

.changeset/do_not_stop_generation_for_invalid_enum_values.md, .changeset/generate_properties_for_some_boolean_enums.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/enums/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/tests/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/enums/bool_enum_tests_bool_enum_post.py, end_to_end_tests/golden-record/my_test_api_client/api/enums/int_enum_tests_int_enum_post.py, openapi_python_client/parser/properties/__init__.py, openapi_python_client/parser/properties/enum_property.py, openapi_python_client/schema/openapi_schema_pydantic/schema.py, tests/test_parser/test_properties/test_enum_property.py
=> Handle bool enums better

.changeset/fix_invalid_type_check_for_nested_unions.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/a_discriminated_union_type_1.py, end_to_end_tests/golden-record/my_test_api_client/models/a_discriminated_union_type_2.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_discriminated_union.py, openapi_python_client/parser/properties/union.py
=> bad code generated for nested unions

.changeset/fix_invalid_type_check_for_nested_unions.md, CHANGELOG.md, pyproject.toml
This PR was created by Knope. Merging it will create a new release
Nested union types (unions of unions) were generating `isinstance()` checks that were not valid (at least for Python 3.9).
Thanks to @codebutler for PR #959 which fixes #958 and #967.
=> chore: prepare release 0.17.3

.changeset/allow_hyphens_in_path_parameters.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/naming/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/naming/hyphen_in_path.py, openapi_python_client/__init__.py, openapi_python_client/parser/openapi.py, openapi_python_client/templates/endpoint_module.py.jinja
Fixes #976 and #578, and replaces #978.
@dbanty please choose your preferred approach between this and PR #987.
The original issue is that `openapi-python-client` throws `incorrect path templating` warnings when the path has a parameter with a hyphen and consequently fails to generate the endpoints.
---
The first commit ensures that hyphens are recognised as allowed delimiters in parameter path names. This allows the endpoints to be generated. 
However, this generates lines like these:
```python
def _get_kwargs(
user_id: int,
) -> Dict[str, Any]:
_kwargs: Dict[str, Any] = {
"method": "post",
"url": "/activitypub/user-id/{user-id}/inbox".format(user-id=user_id,),
}
return _kwargs
```
Since Python variable names cannot contain hyphens, the `user-id` parameter name here will trigger errors …
=> Fix hyphens in path parameters

.changeset/add_response_content_to_unexpectedstatus_exception.md, end_to_end_tests/golden-record/my_test_api_client/errors.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/errors.py, integration-tests/integration_tests/errors.py, openapi_python_client/templates/errors.py.jinja
Fixes #839 and #840
This is a simple change that adds the response content to the `UnexpectedStatus` exception, which is currently the most upvoted feature in [Discussions](https://github.com/openapi-generators/openapi-python-client/discussions).
=> Add response content to UnexpectedStatus exception

.changeset/add_aliases_to_client_for_pyright.md, end_to_end_tests/golden-record/my_test_api_client/client.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/client.py, integration-tests/integration_tests/client.py, openapi_python_client/templates/client.py.jinja
https://www.attrs.org/en/stable/examples.html
=> Add aliases for Client

.changeset/add_config_option_to_override_content_types.md, README.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/config.yml, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/__init__.py, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/config/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/config/content_type_override.py, openapi_python_client/config.py, openapi_python_client/parser/bodies.py, openapi_python_client/parser/responses.py, openapi_python_client/utils.py, tests/test_parser/test_responses.py, tests/test_utils.py
Implemented content_type_overrides from #657 #810
=> content_type_overrides

.changeset/const_values_are_now_validated_at_runtime.md, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/api/const/post_const_path.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/models/post_const_path_body.py, openapi_python_client/parser/properties/const.py, openapi_python_client/templates/property_templates/const_property.py.jinja
For 'const' properties, the parsed value will now be checked against the value in the schema at runtime and a ValueError will be raised if they do not match. Until now, the values would just be `cast` to a `Literal` without checking.
This helps with with parsing `oneOf` when matching a const property is the only way to resolve which of the types should be returned. i.e. if a `oneOf` contains two schemas, but the properties in one are a subset of the other, then the only way to know which one to return is to validate the `const` value.
I know that for the most part this library parses but doesn't validate, but I don't see a way around it in this case. The spec itself mentions validation when talking about `oneOf`:
```
In OAS 3.0, a response payload MAY be described to be exactly one of any …
```
=> validate value of 'const' properties (helps with discriminated unions)

.changeset/switch_yaml_parsing_to_12.md, openapi_python_client/__init__.py, openapi_python_client/config.py, pdm.lock, pyproject.toml, tests/test_config.py
fixes #1041 
ruamel.yaml understands yaml1.2 which yaml doesn't support.
yaml 1.2 lacks norway issue
=> Switch YAML parser to ruamel.yaml which uses YAML 1.2

.changeset/fix_nullable_and_required_properties_in_multipart_bodies.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/golden-record/my_test_api_client/models/body_upload_file_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/models/post_bodies_multiple_files_body.py, integration-tests/integration_tests/models/post_body_multipart_body.py, openapi_python_client/parser/properties/model_property.py, openapi_python_client/parser/properties/protocol.py, openapi_python_client/templates/endpoint_macros.py.jinja, openapi_python_client/templates/model.py.jinja, openapi_python_client/templates/property_templates/any_property.py.jinja, openapi_python_client/templates/property_templates/boolean_property.py.jinja, openapi_python_client/templates/property_templates/date_property.py.jinja, openapi_python_client/templates/property_templates/datetime_property.py.jinja, openapi_python_client/templates/property_templates/enum_property.py.jinja, openapi_python_client/templates/property_templates/file_property.py.jinja, openapi_python_client/templates/property_templates/float_property.py.jinja, openapi_python_client/templates/property_templates/int_property.py.jinja, openapi_python_client/templates/property_templates/list_property.py.jinja, openapi_python_client/templates/property_templates/model_property.py.jinja, openapi_python_client/templates/property_templates/union_property.py.jinja, tests/test_parser/test_properties/test_model_property.py
=> Fix nullable & required properties in multipart bodies

.changeset/added_an_output_path_option_to_generate.md, .changeset/added_an_overwrite_flag_to_generate.md, .changeset/remove_the_update_command.md, .github/workflows/checks.yml, end_to_end_tests/invalid_openapi.yaml, end_to_end_tests/test_end_to_end.py, integration-tests/config.yaml, integration-tests/integration_tests/py.typed, openapi_python_client/__init__.py, openapi_python_client/cli.py, openapi_python_client/config.py, pdm.lock, pyproject.toml, tests/conftest.py, tests/test_cli.py
* Removes `update`
* Adds `--output-path` to `generate`
* Adds `--overwrite` to `generate`
Also removing Safety from CI because it's currently failing in CI, and the current command is about to be removed and instead require an account.
=> Remove update, add `--overwrite` and `--output-path`

end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/golden-record/my_test_api_client/models/body_upload_file_tests_upload_post.py, openapi_python_client/templates/property_templates/list_property.py.jinja
The `_transform` macro is called at three different places in this file, but one location was not similarly indented as the other two. This caused errors in the ruff post_hook like:
```
error: Failed to parse foo/models/foo_request.py:125:9: Expected an indented block after `if` statement
```
The generated code without the indent fix looks like:
```
if not isinstance(self.foo, Unset):
_temp_foo = []  # <-- incorrect indent
for foo_item_data in self.foo:
foo_item: Union[None, int]
foo_item = foo_item_data
_temp_foo.append(foo_item)
foo = (None, json.dumps(_temp_foo).encode(), 'application/json')
```
=> fix: Indent of generated code for non-required lists. Thanks @sfowl!

end_to_end_tests/__snapshots__/test_end_to_end.ambr, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/documents_with_errors/invalid-uuid-defaults.yaml, end_to_end_tests/golden-record/my_test_api_client/models/a_model.py, end_to_end_tests/golden-record/my_test_api_client/models/extended.py, openapi_python_client/parser/properties/__init__.py, openapi_python_client/parser/properties/property.py, openapi_python_client/parser/properties/uuid.py, openapi_python_client/templates/property_templates/uuid_property.py.jinja, pyproject.toml
Replaces #1131 with a few fixes
=> feat: Add UUID string format. Thanks @estyrke!

end_to_end_tests/golden-record/my_test_api_client/client.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/client.py, integration-tests/integration_tests/client.py, openapi_python_client/templates/client.py.jinja
minor fix, simply adding a missing word in docstring...
=> fix: Typo in docstring

openapi_python_client/schema/openapi_schema_pydantic/schema.py
Resolves #651 
From that issue:
The OpenAPI spec [section](https://swagger.io/specification/) on the `Schema` object says:
> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is a superset of the [JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00).
> 
> For more information about the properties, see [JSON Schema Core](https://tools.ietf.org/html/draft-bhutton-json-schema-00) and [JSON Schema Validation](https://tools.ietf.org/html/draft-bhutton-json-schema-validation-00).
The JSON Schema Validation spec [says](https://json-schema.org/draft/2020-12/json-schema-validation#name-required) of the `required` property:
> The value of this keyword MUST be …
=> fix: allow required fields list to be specified as empty (#651)

end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/default/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/default/get_models_oneof_with_required_const.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/get_models_oneof_with_required_const_response_200_type_0.py, end_to_end_tests/golden-record/my_test_api_client/models/get_models_oneof_with_required_const_response_200_type_1.py, openapi_python_client/parser/properties/const.py
The [template](https://github.com/openapi-generators/openapi-python-client/blob/main/openapi_python_client/templates/property_templates/const_property.py.jinja#L2) for `const` properties uses `cast` unconditionally, but the import for `cast` in `ConstProperty.get_imports` was conditioned on whether the property was required or not, leading to broken generated code for required const properties.
I'd be happy to add a test for this if desired! A cursory glance suggests that maybe the end_to_end tests would be the right place?
Resolves #1150
=> fix: import cast for required const properties, since it's used in the template

.changeset/fix_minimum_attrs_version.md, end_to_end_tests/golden-record/pyproject.toml, end_to_end_tests/literal-enums-golden-record/pyproject.toml, end_to_end_tests/metadata_snapshots/pdm.pyproject.toml, end_to_end_tests/metadata_snapshots/poetry.pyproject.toml, end_to_end_tests/metadata_snapshots/setup.py, end_to_end_tests/test-3-1-golden-record/pyproject.toml, integration-tests/pyproject.toml, openapi_python_client/templates/pyproject.toml.jinja, openapi_python_client/templates/setup.py.jinja, pdm.lock, pdm.minimal.lock, pyproject.toml
=> Fix minimum attrs version

pdm.lock, pyproject.toml, tests/test_config.py
The usage of the `ruamel-yaml-string` package is isolated to one test only. The same functionality is easily be provided with a simple class method.
=> Remove ruamel-yaml-string package

tests/test___init__.py
This commit renames the invocation of `python` to `python3` in the tests.
While many systems now alias `python` to `python3`, this behavior is not
guaranteed across all environments and is often configured by the user,
rather than provided by the operating system directly.
Explicitly using `python3` ensures that the tests are executed with the
intended Python 3 interpreter, regardless of user-specific configurations,
and therefore improves the portability and reliability of the test suite.
=> test: Rename python to python3 in tests

end_to_end_tests/golden-record/my_test_api_client/api/bodies/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/config/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/default/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/defaults/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/enums/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/location/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/naming/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/parameter_references/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/parameters/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/responses/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/tag1/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/tag2/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/tests/__init__.py, end_to_end_tests/golden-record/my_test_api_client/api/true_/__init__.py, end_to_end_tests/literal-enums-golden-record/my_enum_api_client/api/enums/__init__.py, end_to_end_tests/literal-enums-golden-record/my_enum_api_client/api/tests/__init__.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/api/const/__init__.py, end_to_end_tests/test-3-1-golden-record/test_3_1_features_client/api/prefix_items/__init__.py, integration-tests/integration_tests/api/body/__init__.py, integration-tests/integration_tests/api/parameters/__init__.py, openapi_python_client/templates/endpoint_init.py.jinja
This commit adds a docstring to the jinja template file to prevent it from being empty.
=> docs: add module docstring for endpoint init template

.changeset/always_parse_ref_as_a_reference.md, end_to_end_tests/baseline_openapi_3.0.json, openapi_python_client/schema/openapi_schema_pydantic/components.py, openapi_python_client/schema/openapi_schema_pydantic/encoding.py, openapi_python_client/schema/openapi_schema_pydantic/media_type.py, openapi_python_client/schema/openapi_schema_pydantic/operation.py, openapi_python_client/schema/openapi_schema_pydantic/parameter.py, openapi_python_client/schema/openapi_schema_pydantic/path_item.py, openapi_python_client/schema/openapi_schema_pydantic/reference.py, openapi_python_client/schema/openapi_schema_pydantic/response.py, openapi_python_client/schema/openapi_schema_pydantic/responses.py, openapi_python_client/schema/openapi_schema_pydantic/schema.py, pdm.lock, pdm.minimal.lock, pyproject.toml, tests/test_schema/test_noisy_refs.py
I’ve found a corner case, I think due to changes to Pydantic’s [smart mode](https://docs.pydantic.dev/latest/concepts/unions/#smart-mode) for disambiguating unions, where a subdocument with a `$ref` key and additional keys (title, description, etc) is validated as a `Schema` instead of as a `Reference` model.  I believe these should be ignored per ["any properties added SHALL be ignored"](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#reference-object) ()   This was a problem for me since I want to use a reference to an enum as a header parameter in FastAPI. The OpenAPI document generated by FastAPI included several fields (title, description, etc) along with `$ref`. The`Schema` instance it was validate to lacked any actual type constraint information, so …
=> avoid misparsing references as other types using Pydantic discriminated unions

.changeset/fix-models-enums-lists.md, end_to_end_tests/custom-templates-golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/test_custom_templates/models_init.py.jinja, end_to_end_tests/test_end_to_end.py, openapi_python_client/parser/openapi.py
Resolves #1188.
The change is simply to store a list, rather than a generator expression.
The new `models_init.py.jinja` template in the end-to-end tests shows that this now works. Without the fix in `openapi.py`, this template is rendered with nothing under the `Using "openapi.models"` and `Using "openapi.enums"` headings.
This fix is somewhat important for our use case, because we need to put some code in `models/__init__.py` that is aware of what the model class names and modules are. Without the fix, the only way to get this would be to iterate over `imports`, which gives you strings like `from .module_name import ClassName`, and then parse those strings, which is workable but pretty clunky.
=> pass models & enums as lists so custom templates can use them

end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/golden-record/my_test_api_client/api/tests/octet_stream_tests_octet_stream_post.py, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/body_upload_file_tests_upload_post.py, end_to_end_tests/golden-record/my_test_api_client/models/octet_stream_tests_octet_stream_post_response_200.py, openapi_python_client/parser/properties/file.py
=> fix: Import error for `types.FileType` (#1274)

.gitignore, end_to_end_tests/docstrings-on-attributes-golden-record/pyproject.toml, end_to_end_tests/golden-record/pyproject.toml, end_to_end_tests/literal-enums-golden-record/pyproject.toml, end_to_end_tests/metadata_snapshots/poetry.pyproject.toml, end_to_end_tests/metadata_snapshots/uv.pyproject.toml, end_to_end_tests/regen_golden_record.py, end_to_end_tests/test-3-1-golden-record/pyproject.toml, end_to_end_tests/test_end_to_end.py, openapi_python_client/__init__.py, openapi_python_client/config.py, openapi_python_client/templates/README.md.jinja, openapi_python_client/templates/pyproject.toml.jinja, openapi_python_client/templates/pyproject_pdm.toml.jinja, openapi_python_client/templates/pyproject_poetry.toml.jinja, openapi_python_client/templates/pyproject_uv.toml.jinja
This PR adds support for `--meta uv` which then generates a `uv` compatible package with the `hatchling` build backend. Eventually, with newer versions of `uv`, it will probably use the `uv_build` backend.
Resolves #1241 
cc @johnthagen @dbanty
=> feat: Add --meta uv for generating astral-sh/uv compatible packages.

end_to_end_tests/metadata_snapshots/uv.pyproject.toml, openapi_python_client/templates/pyproject_uv.toml.jinja
This has become the `uv` default in `0.8.0`.
See https://github.com/astral-sh/uv/releases/tag/0.8.0
=> feat(uv): Switch to `uv_build` build backend.

.changeset/change_some_union_variant_names.md, end_to_end_tests/baseline_openapi_3.0.json, end_to_end_tests/baseline_openapi_3.1.yaml, end_to_end_tests/golden-record/my_test_api_client/models/__init__.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property_inlined.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property_inlined_apples.py, end_to_end_tests/golden-record/my_test_api_client/models/model_with_union_property_inlined_bananas.py, openapi_python_client/parser/properties/union.py, tests/conftest.py, tests/test_parser/test_properties/test_union.py
Replaces #962 with a rebase & a couple tweaks
=> Union variants use Title names instead of indices

tests/test_cli.py
Fixes test failure in test_bad_config caused by Click 8.2.0+ behavior change. Click 8.2.0+ now keeps stdout and stderr streams separate by default.
Fixes #1308
=> test: fix test_bad_config failure due to Click 8.2.0 breaking change

end_to_end_tests/functional_tests/generated_code_execution/test_properties.py, end_to_end_tests/functional_tests/generator_failure_cases/test_invalid_references.py, openapi_python_client/parser/properties/__init__.py, tests/test_parser/test_properties/test_init.py
This PR adds support for reference schemas (https://github.com/openapi-generators/openapi-python-client/discussions/800).
The idea with this change is that during parsing of the schemas, when the parser encounters a `Reference` schema, rather than aborting it will attempt to fully resolve that reference by following the chain of references until it encounters a `Schema`. When it does, it will attempt to fetch that parsed `Schema` from the dictionary of available components, which should include all possible referent schemas. If it exists, it will parse the current/original reference Schema as if it was its ultimate referent. If it reaches a reference that does not exist, it logs an error and moves on: it won't be able to parse this `Reference`.
The result of this is that every reference …
=> feat: Reference schema support (#800)

end_to_end_tests/metadata_snapshots/uv.pyproject.toml, openapi_python_client/templates/pyproject_uv.toml.jinja
Clients generated like this:
```
uv run openapi-python-client generate --path openapi.json --overwrite --output-path client --meta uv
```
Generate these warnings during installation with `uv`:
> warning: The `requires-python` specifier (`~=3.9`) in `client` uses the tilde specifier (`~=`) without a patch version. This will be interpreted as `>=3.9, <4`. Did you mean `~=3.9.0` to constrain the version as `>=3.9.0, <3.10`? We recommend only using the tilde specifier with a patch version to avoid ambiguity.
=> fix: ambigious tilde specifier requires-python with`--meta=uv`
